/**
 * models/recommendationModel.js
 * -----------------------------------------------------------------
 * Data access layer for the "recommendations" table.
 * These rows are generated by the rule-based AI engine
 * (services/aiEngine.js) and logged for history/auditing purposes.
 * -----------------------------------------------------------------
 */

const { pool } = require('../config/db');

const RecommendationModel = {
  async logMany(userId, recommendations, healthScore) {
    if (!recommendations.length) return;
    const values = recommendations.map((r) => [userId, r.message, r.category, r.severity, healthScore]);
    await pool.query(
      `INSERT INTO recommendations (user_id, message, category, severity, health_score)
       VALUES ?`,
      [values]
    );
  },

  async findRecentByUser(userId, limit = 10) {
    const [rows] = await pool.query(
      `SELECT * FROM recommendations WHERE user_id = ?
       ORDER BY generated_at DESC LIMIT ?`,
      [userId, limit]
    );
    return rows;
  }
};

module.exports = RecommendationModel;
